language: node_js
node_js:
  - 10.8.0
cache:
directories:
  - node_modules
services:
  - mongodb
  - docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run test
deploy:
  # Production Deploy if we push to master
  - provider: script
    script: ./bin/deploy_production.sh
    on:
      branch: master
  # Develop Deploy if we push to develop
  - provider: script
    script: ./bin/deploy_develop.sh
    on:
      branch: develop
